### ISSUE TITLE
Property Writing

### ISSUE THREAD

**Issue by clafouti2104** [JoelBender/bacpypes#180]
Hi everybody,

I'm trying to create a script which writes a property but I got some errors. Sorry but I'm a really bad python developper.
I take the ReadWriteProperty.py and try to adapt it (I don't want to have a console, the script will write a single property).
The script is attached.
[ReadWriteProperty.zip](https://github.com/JoelBender/bacpypes/files/1870791/ReadWriteProperty.zip)

Here's the results
![2018-04-03_105202](https://user-images.githubusercontent.com/3226573/38239501-316d8100-372d-11e8-98e3-38c74a9bf788.png)

I don't know why I'm having the "no task manager" error.

Thank you

**Comment by JoelBender** [comment]
The "core" of BACpypes has things that need to happen at a specific time, like re-sending a request if it didn't see a response or updating a schedule to a new value, and doing things on a regular basis like clearing out cache entries.  These things are "tasks" and organizing the list of tasks is up to an instance of a `TaskManager` all of which are in the `bacpypes.task` module.

There is only one task manager (an instance of the `TaskManager` class) that is shared throughout the library and because it follows the "singleton pattern" whenever you call the class to build an instance you'll always get the same one:
```
>>> from bacpypes.task import TaskManager
>>> tm1 = TaskManager()
>>> tm2 = TaskManager()
>>> tm1 is tm2
True
```
For the truly adventurous, BACpypes has a provision for you to provide your own task manager by subclassing and creating your instance before the rest of the library needs one and the library will use yours instead:
```
>>> from bacpypes.task import TaskManager
>>> class MyTaskManager(TaskManager):
...     pass
... 
>>> tm1 = MyTaskManager()
>>> tm2 = TaskManager()
>>> tm1 is tm2
True
```
So the reason you are getting the "no task manager" error is because your application is attempting to schedule a task (in this case, what to do if you don't get a response to your request) and one hasn't been created, but it will be created auto-magically by the `run()` function.  So whatever you do you want to make sure the functions get called after the core is up and running, and by calling `deferred()` it will put a function in the list of tasks to execute.

The more difficult problem with your application is that you are using the threaded version of the IOCB functions (specifically `iocb.wait()`) which is based on events. With only one thread the event will never get set so your application will stall.  The solution is to have your WritePropertyRequest running in it's own thread or to add a callback to the IOCB with a function that gets called when the request is complete.

I'm attaching two different versions of your application, look them over and let me know if one fits your way of doing things better than the other or if you have more questions.
[ReadWriteProperty-ans.zip](https://github.com/JoelBender/bacpypes/files/1884217/ReadWriteProperty-ans.zip)

**Comment by clafouti2104** [comment]
Thank you for your answer.
It's more clear now.
I got a last question, I want too have a tcp server which listens for write requests to send. So I try to adapt to adapt your second example, but I cannot close my thread client. So the first request sends the write command, the second sends 2 requests, the third sends 3 times and so on...
Can you help me please?
[scripts.zip](https://github.com/JoelBender/bacpypes/files/1886353/scripts.zip)

**Comment by JoelBender** [comment]
Ah, there's nothing quite like debugging threaded applications and sockets, which is why I avoid them and the _raison d'être_ for the `bacpypes.iocb` module.  There are even more wonderful idiosyncrasies  lurking in TCP connection management, so the `bacpypes.tcp` module simplifies those.  I mashed together the `TCPServer.py` sample code and the stuff you'll recognize, see attached.

[WritePropertyTCPServer.zip](https://github.com/JoelBender/bacpypes/files/1886607/WritePropertyTCPServer.zip)

**Comment by Seikodi** [comment]
Hi Joel and bonjour clafouti ;-) .
I'm quite new to python, bacnet and by the way bacpypes :-) .
Like clafouti I want to create a script that I can use to write a property but this way.

>import  WriteProperty
>ansWrite = WriteProperty.write(argu)
>>if ansWrite != 'ack'
>>print 'erreur d ecriture'

I've done this script inspired by Joel work but can't get the expected result, can you help me please?
[WriteProperty.zip](https://github.com/JoelBender/bacpypes/files/2023130/WriteProperty.zip)
