### ISSUE TITLE
ObjectIdentifier always created of type analogInput in v0.17.5

### ISSUE THREAD

**Issue by amrx101** [JoelBender/bacpypes#242]
In v0.17.5, `ObjectIdentifier` created is always of type `analogInput`.  Its hard coded to `analogInput`  [here ](https://github.com/JoelBender/bacpypes/blob/master/py27/bacpypes/primitivedata.py#L1659).

`(Pdb) ObjectIdentifier(3).value
('analogInput', 3L)`
`
(Pdb) ObjectIdentifier(5).value
('analogInput', 5L)`
`
(Pdb) ObjectIdentifier(5).value
('analogInput', 5L)
`

`ObjectIdentifier` should be a tuple of `(type, instance)`. Currently the type is hardcoded to `analogInput`.

From earlier versions:

`ObjecIdentifier=(obj_id, instance_no)`

vs Now

`ObjectIdentifier=(obj_id)`

**Comment by JoelBender** [comment]
The `self.value = ('analogInput', 0)` is just an initial default value so if someone creates an `ObjectIdentifier` it has something.  It encodes as a zero, which would mostly match the concept of a zero default value for an integer, empty string or list, etc.  It's not hard coded because the value is updated from the `*args`.

If you create an object identifier by passing in an integer it will be "unpacked" according to the BACnet rules:
```
>>> from bacpypes.primitivedata import ObjectIdentifier

>>> ObjectIdentifier('program', 99).get_long()
67108963

>>> ObjectIdentifier(67108963).value
('program', 99)
```
