### ISSUE TITLE
MAC Address from I-Am

### ISSUE THREAD

**Issue by torablien** [JoelBender/bacpypes#511]
Is there a way I can get the MAC address from the I-Am using BACpypes? 

---
I setup a test IP2IP network with the sample IP2IPRouter where end device (192.168.2.45:47810) is behind the Router (192.168.86.71:47811) with 1 and 2 as net1 and net2. On YABE, this shows the device as "192.168.2.45:47810 via 192.168.86.71:47811" as expected.
 
I can issue commands to it with the address "1:192.168.2.45:47810" and also get that back as the `pduSource`. I am looking to address the device via MAC address. **I can issue a global broadcast Who-Is and then grab the MAC address using Wireshark from the I-Am NPDU SADR.** I am able to then issue commands using the MAC address (e.g. "1:0xc0a8022dbac2") instead of the IP+Port. I am looking to get this address programmatically rather than having to manually inspect with Wireshark.

**Comment by JoelBender** [comment]
Not directly, the library is built on the sockets library and this information is not available.  There are "raw" sockets that you can bind to an interface and then filter the content, but you really don't want to do that in Python.  I have an old project [here](https://github.com/JoelBender/bacpypes-pcap) that could be resurrected, I usually use it to inspect capture files from **deamonlogger** that runs on servers, so that's a little better than manually, and I think there's a way to run it in real time.  It's been a while!

**Comment by torablien** [comment]
Thanks Joel, I will look for alternative options to automatically capture the MAC address.
